# Generated by Django 5.0.4 on 2024-04-25 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_post_requested_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='requested_date',
        ),
    ]
