# Generated by Django 4.2.8 on 2024-04-26 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0005_post_recommendation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
